[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx vite build', 'npx tsc -p tsconfig.json']

[start]
cmd = 'node dist/server.js'
